// Generated by buildHomerDescribe.cmd. Do not edit; change AppVersion in HomerDescribe_setup.iss.
using System.Reflection;
[assembly: AssemblyTitle("HomerDescribe")]
[assembly: AssemblyDescription("Audio description for local video files")]
[assembly: AssemblyCompany("Jamal Mazrui")]
[assembly: AssemblyProduct("HomerDescribe")]
[assembly: AssemblyCopyright("Released under the MIT license")]
[assembly: AssemblyVersion("1.0.0")]
[assembly: AssemblyFileVersion("1.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
