@echo off
rem ===================================================================
rem buildHomerScribe.cmd -- build HomerScribe.exe.
rem
rem Follows the pattern proven by buildDbDo.cmd and buildUrlFido.cmd.
rem
rem VERSION: version.txt is the SINGLE source of truth. It holds one
rem line, nothing else. This script increments it on every build --
rem stepping over any number already released, which it learns from the
rem repository's own tags -- then generates Version.cs from it, so the
rem running program reports the same number. HomerScribe_setup.iss reads version.txt directly, so
rem the installer reports it too, and tagRelease reads it back out of
rem the built setup's version resource to form the tag. No version
rem literal appears anywhere else, so a stale file cannot rewind it.
rem
rem   buildHomerScribe.cmd          increments the version, then builds
rem   buildHomerScribe.cmd nobump   keeps the current number
rem
rem COMPILER: Roslyn is preferred, from Visual Studio or the free Build
rem Tools. The pre-Roslyn csc.exe under Microsoft.NET\Framework64 is
rem accepted as a fallback, since HomerScribe.cs uses no language
rem feature beyond C# 5. The Homer modules do, so if the fallback is
rem used and Lbc.cs or Say.cs fails to compile, install Build Tools:
rem https://visualstudio.microsoft.com/downloads/
rem
rem REFERENCES: three assemblies are NOT on the compiler's default
rem reference path and must be given by full path, or the build fails
rem with CS0006:
rem   System.Speech.dll        -- the Windows voices
rem   UIAutomationProvider.dll -- Say.cs, Narrator notification events
rem   UIAutomationTypes.dll    -- Say.cs
rem
rem PARSE-TIME PITFALL: the variable NAME ProgramFiles(x86) contains
rem parentheses, and cmd.exe scans a parenthesised block for its closing
rem paren BEFORE expanding variables. Every search below is therefore a
rem single-line "if not defined X if exist ... set" chain, never a block.
rem
rem Output in this folder: HomerScribe.exe, and the installer if Inno
rem Setup is present. Everything is logged to buildHomerScribe.log.
rem ===================================================================

setlocal enabledelayedexpansion
cd /d "%~dp0"

set "app=HomerScribe"
rem THE LOG GOES IN logs\, WITH A TIMESTAMP. A fixed name at the project root
rem overwrites the build before it -- which is the one you want when a build
rem has failed twice. Homer convention: <App>-<task>-yyyyMMdd-HHmmss.log, one
rem per run, so an alphabetical sort is a chronological one.
set "sLogDir=%CD%\logs"
if not exist "%sLogDir%" mkdir "%sLogDir%" >nul 2>&1
rem WMIC IS GONE. Windows 11 removed it, so this fell straight through to the
rem fallback and every log was called ...-00000000-000000.log -- one name, so
rem each build overwrote the last, which is exactly what the timestamp was for.
rem PowerShell's Get-Date is present on every supported Windows.
for /f %%T in ('powershell -NoProfile -Command "Get-Date -Format yyyyMMdd-HHmmss" 2^>nul') do set "sNow=%%T"
if not defined sNow for /f "tokens=2 delims==" %%T in ('wmic os get localdatetime /value 2^>nul') do set "sNow=%%T-"
if not defined sNow set "sNow=unknown-time"
set "log=%sLogDir%\HomerScribe-build-%sNow%.log"
echo %app% build started %DATE% %TIME%> "%log%"
echo Script: %~f0>> "%log%"
echo Folder: %CD%>> "%log%"
echo Command line: %0 %*>> "%log%"
echo Build log: %log%

rem ---- version: version.txt is the single source of truth -----------
if not exist "version.txt" (
  echo ERROR: version.txt not found. It must hold the current version, e.g. 1.0.0
  echo ERROR: version.txt not found.>> "%log%"
  goto :failed
)
set "ver="
set /p ver=<version.txt
set "ver=!ver: =!"
if "!ver!"=="" (
  echo ERROR: version.txt is empty.
  echo ERROR: version.txt is empty.>> "%log%"
  goto :failed
)
if /i "%~1"=="nobump" goto :keepVersion
call :takeNextVersion
goto :haveVersion

:keepVersion
echo Version: !ver! ^(nobump: keeping the current number^)
echo Version: !ver! ^(nobump^)>> "%log%"

:haveVersion

rem ---- generate Version.cs from version.txt -------------------------
rem Generated output: do not edit it, and do not commit it.
> Version.cs echo // Generated by buildHomerScribe.cmd from version.txt.  Do not edit; do not commit.
>> Version.cs echo public static class BuildVersion
>> Version.cs echo {
>> Version.cs echo     public const string Version = "!ver!";
>> Version.cs echo }
echo Wrote Version.cs for !ver!>> "%log%"

rem ---- locate the compiler ------------------------------------------
set "csc="
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe" set "csc=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not defined csc (
  echo ERROR: no C# compiler was found.
  echo ERROR: no C# compiler was found.>> "%log%"
  goto :failed
)
echo Compiler: !csc!
echo Compiler: !csc!>> "%log%"

rem ---- locate the reference assemblies given by full path -----------
rem Copy the paren-bearing root into a paren-free name before any block.
set "progFiles86=%ProgramFiles(x86)%"
set "progFiles=%ProgramFiles%"
set "refBase=Reference Assemblies\Microsoft\Framework\.NETFramework"

set "speech="
set "uiaProv="
set "uiaTypes="

for %%v in (v4.8 v4.7.2 v4.7.1 v4.7 v4.6.2 v4.6.1 v4.6 v4.5.2) do (
  if not defined speech if exist "!progFiles86!\!refBase!\%%v\System.Speech.dll" set "speech=!progFiles86!\!refBase!\%%v\System.Speech.dll"
  if not defined speech if exist "!progFiles!\!refBase!\%%v\System.Speech.dll" set "speech=!progFiles!\!refBase!\%%v\System.Speech.dll"
  if not defined uiaProv if exist "!progFiles86!\!refBase!\%%v\UIAutomationProvider.dll" set "uiaProv=!progFiles86!\!refBase!\%%v\UIAutomationProvider.dll"
  if not defined uiaProv if exist "!progFiles!\!refBase!\%%v\UIAutomationProvider.dll" set "uiaProv=!progFiles!\!refBase!\%%v\UIAutomationProvider.dll"
  if not defined uiaTypes if exist "!progFiles86!\!refBase!\%%v\UIAutomationTypes.dll" set "uiaTypes=!progFiles86!\!refBase!\%%v\UIAutomationTypes.dll"
  if not defined uiaTypes if exist "!progFiles!\!refBase!\%%v\UIAutomationTypes.dll" set "uiaTypes=!progFiles!\!refBase!\%%v\UIAutomationTypes.dll"
)

rem Fallbacks: the assembly cache and the runtime WPF folder.
if not defined speech if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\System.Speech\v4.0_4.0.0.0__31bf3856ad364e35\System.Speech.dll" set "speech=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\System.Speech\v4.0_4.0.0.0__31bf3856ad364e35\System.Speech.dll"
if not defined uiaProv if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationProvider.dll" set "uiaProv=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationProvider.dll"
if not defined uiaTypes if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationTypes.dll" set "uiaTypes=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationTypes.dll"
if not defined uiaProv if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll" set "uiaProv=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll"
if not defined uiaTypes if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll" set "uiaTypes=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll"

if not defined speech (
  echo ERROR: System.Speech.dll was not found.
  echo         Install the .NET Framework 4.8 Developer Pack:
  echo         https://dotnet.microsoft.com/download/dotnet-framework/net48
  echo ERROR: System.Speech.dll was not found.>> "%log%"
  goto :failed
)
if not defined uiaProv (
  echo ERROR: UIAutomationProvider.dll was not found. Install the .NET Framework 4.8 Developer Pack.
  echo ERROR: UIAutomationProvider.dll was not found.>> "%log%"
  goto :failed
)
if not defined uiaTypes (
  echo ERROR: UIAutomationTypes.dll was not found. Install the .NET Framework 4.8 Developer Pack.
  echo ERROR: UIAutomationTypes.dll was not found.>> "%log%"
  goto :failed
)
echo Speech: !speech!>> "%log%"
echo UI Automation: !uiaProv!>> "%log%"

rem ---- the installer's helper scripts --------------------------------
if not exist "installOllama.cmd" echo WARN: installOllama.cmd is missing; the installer's Ollama checkbox will not work.>> "%log%"
if not exist "installModels.cmd" echo WARN: installModels.cmd is missing; the installer's model checkbox will not work.>> "%log%"
if not exist "context\*.md" echo NOTE: the context folder holds no .md example. The installer skips it.>> "%log%"

rem ---- the companion programs the installer packages -------------------
rem ffmpeg does the video and audio work; yt-dlp fetches video from a web
rem address. Neither is committed to the repository -- ffmpeg alone is far past
rem what a repository should carry -- so they are fetched here when missing.
rem The downloads are idempotent: a file already present is left alone.
rem
rem ffmpeg comes from BtbN's LGPL build rather than a GPL one. Both work
rem identically here, and the LGPL build carries lighter obligations when the
rem installer is redistributed. See License.md.

if exist "ffmpeg.exe" if exist "ffprobe.exe" goto :haveFfmpeg
rem Already on this machine? A second working copy is the ordinary case, and
rem these are a hundred megabytes that change rarely. Copying beats fetching.
set "haveTools="
if not defined haveTools if exist "C:\HomerScribe\ffmpeg.exe" set "haveTools=C:\HomerScribe"
if not defined haveTools if exist "%LOCALAPPDATA%\Programs\HomerScribe\ffmpeg.exe" set "haveTools=%LOCALAPPDATA%\Programs\HomerScribe"
if not defined haveTools if exist "%ProgramFiles%\HomerScribe\ffmpeg.exe" set "haveTools=%ProgramFiles%\HomerScribe"
if defined haveTools echo Copying ffmpeg from %haveTools% rather than downloading it.
if defined haveTools echo Copying ffmpeg from %haveTools%>> "%log%"
if defined haveTools copy /y "%haveTools%\ffmpeg.exe" "ffmpeg.exe" >nul 2>&1
if defined haveTools if exist "%haveTools%\ffprobe.exe" copy /y "%haveTools%\ffprobe.exe" "ffprobe.exe" >nul 2>&1
if defined haveTools if exist "%haveTools%\yt-dlp.exe" if not exist "yt-dlp.exe" copy /y "%haveTools%\yt-dlp.exe" "yt-dlp.exe" >nul 2>&1
if exist "ffmpeg.exe" if exist "ffprobe.exe" goto :haveFfmpeg

echo Fetching ffmpeg and ffprobe. This is a large download and happens once.
echo Fetching ffmpeg and ffprobe>> "%log%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';" ^
  "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;" ^
  "$url = 'https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl.zip';" ^
  "$tmpZip = Join-Path $env:TEMP 'homerFfmpeg.zip';" ^
  "$tmpDir = Join-Path $env:TEMP 'homerFfmpeg';" ^
  "if (Test-Path $tmpZip) { Remove-Item -Force $tmpZip };" ^
  "if (Test-Path $tmpDir) { Remove-Item -Recurse -Force $tmpDir };" ^
  "Invoke-WebRequest -Uri $url -OutFile $tmpZip -UseBasicParsing;" ^
  "Expand-Archive -Path $tmpZip -DestinationPath $tmpDir;" ^
  "foreach ($name in @('ffmpeg.exe','ffprobe.exe')) {" ^
  "  $item = Get-ChildItem -Path $tmpDir -Recurse -Filter $name;" ^
  "  if ($item -is [array]) { $item = $item[0] };" ^
  "  $found = $null; if ($item -ne $null) { $found = $item.FullName };" ^
  "  if ($null -eq $found) { throw ($name + ' was not in the archive') };" ^
  "  Copy-Item -Path $found -Destination $name -Force;" ^
  "}" ^
  "Remove-Item -Force $tmpZip;" ^
  "Remove-Item -Recurse -Force $tmpDir;" >> "%log%" 2>&1
if errorlevel 1 (
  echo WARNING: ffmpeg could not be downloaded; see %log%.
  echo WARNING: ffmpeg could not be downloaded.>> "%log%"
  echo   trying winget>> "%log%"
  winget install --id Gyan.FFmpeg --accept-source-agreements --accept-package-agreements --silent >> "%log%" 2>&1
  rem NOT COPIED HERE. winget has just installed ffmpeg machine-wide, which is
  rem where a shared component belongs — one copy, found by every Homer app, and
  rem safe from any single app's upgrade. Copying it into this folder undid that.
  rem HomerScribe finds it on the PATH and in the usual Program Files locations.
  rem ffprobe likewise: left where winget put it.
  if not exist "ffmpeg.exe" echo WARNING: ffmpeg is still absent; the log says what was tried.
)
:haveFfmpeg
if exist "ffmpeg.exe" echo ffmpeg.exe is present>> "%log%"
if not exist "ffmpeg.exe" echo WARN: ffmpeg.exe is absent; the installer will not package it.>> "%log%"

if exist "yt-dlp.exe" goto :haveYtDlp
echo Fetching yt-dlp.
echo Fetching yt-dlp>> "%log%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop'; $ProgressPreference='SilentlyContinue';" ^
  "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;" ^
  "$url = 'https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe';" ^
  "Invoke-WebRequest -Uri $url -OutFile 'yt-dlp.exe' -UseBasicParsing;" >> "%log%" 2>&1
if errorlevel 1 (
  echo WARNING: yt-dlp could not be downloaded; see %log%.
  echo WARNING: yt-dlp could not be downloaded.>> "%log%"
  echo   trying winget>> "%log%"
  winget install --id yt-dlp.yt-dlp --accept-source-agreements --accept-package-agreements --silent >> "%log%" 2>&1
  rem yt-dlp likewise: left where winget put it.
  if not exist "yt-dlp.exe" echo WARNING: yt-dlp is still absent; the log says what was tried.
)
:haveYtDlp
if exist "yt-dlp.exe" echo yt-dlp.exe is present>> "%log%"

rem ---- keep yt-dlp current ---------------------------------------------
rem YouTube changes what it serves, sometimes deliberately to break
rem downloaders, and yt-dlp ships the fixes within days. A copy a few weeks
rem old is a copy from before several of those changes, and the symptom is a
rem video that used to download being refused.
rem
rem So it is updated on EVERY build rather than left to age. yt-dlp updates
rem itself: "-U" takes the newest stable, "--update-to nightly" the newest
rem nightly. Nightly is what yt-dlp's own README recommends for regular users,
rem and it is the channel to be on when something has just broken.
rem
rem This is one quick call that prints "yt-dlp is up to date" and stops when
rem there is nothing to do. It never fails the build: no network, or a copy
rem that cannot write to itself, and the build carries on with what is there.
if not exist "yt-dlp.exe" goto :ytDlpDone
echo Making sure yt-dlp is current.
echo ---- yt-dlp update ---->> "%log%"
"yt-dlp.exe" --version >> "%log%" 2>&1
"yt-dlp.exe" --update-to nightly >> "%log%" 2>&1
if errorlevel 1 (
  echo yt-dlp could not update itself; the copy already here will be used.
  echo NOTE: yt-dlp did not update. Carrying on with the copy already here.>> "%log%"
)
echo yt-dlp version after the update attempt:>> "%log%"
"yt-dlp.exe" --version >> "%log%" 2>&1
:ytDlpDone

rem ---- ExifTool --------------------------------------------------------
rem Writes the descriptions into the pictures themselves.
rem
rem ONE FILE, AND ONLY ONE FILE. Jamal's requirement, and it settles what may
rem be used here. exiftool.exe must be a self-contained binary with nothing
rem beside it -- no "exiftool_files" folder, no Perl DLLs.
rem
rem That rules out everything currently published, and it is worth writing
rem down why so nobody undoes this later:
rem
rem   exiftool.org / SourceForge 13.59  a small launcher PLUS an
rem                                     "exiftool_files" folder holding Perl
rem   winget OliverBetz.ExifTool        the same thing, installed
rem   Image-ExifTool-<ver>.tar.gz       Perl source, needs Perl installed
rem
rem NOBODY publishes a current single-file build. The one-file form is the OLD
rem exiftool.org format, a PAR-packed archive, and it was replaced by the
rem launcher deliberately: unpacking a PAR archive on every invocation is slow,
rem and HomerScribe invokes ExifTool once per picture. A third-party single
rem file exists on GitHub but is a personal archive with no following, and is
rem not something to hang a build on.
rem
rem NONE OF THIS COSTS ANYTHING, because HomerScribe no longer needs a recent
rem ExifTool: it carries the definitions of the two IPTC accessibility
rem properties itself and hands them over with -config. An older single-file
rem copy writes all nine fields.
rem
rem So: use a single-file copy if one is here, say which and how old, and
rem never fetch or keep the folder kind.

rem ---- ExifTool ------------------------------------------------------
rem THE SINGLE-FILE BUILD IS DEPRECATED. Phil Harvey stopped releasing it in
rem July 2024 (about 12.88). The current packaging keeps its Perl runtime in an
rem exiftool_files folder beside the executable, which is faster and stops
rem antivirus flagging it. So this build does not hunt for a single file any
rem more: the INSTALLER offers ExifTool through
rem   winget install --id OliverBetz.ExifTool --scope machine
rem and the program finds it in %ProgramFiles%\ExifTool.
rem
rem A single-file copy placed in exec\ by hand is still honoured, as a
rem fallback, and shipped by the installer from there.
if exist "exec\exiftool.exe" (
  echo exiftool.exe is present in exec\, placed there by hand>> "%log%"
  echo exiftool.exe is present, from exec\
  goto :exifToolDone
)
echo NOTE: no exiftool.exe in exec\. That is fine: the installer offers ExifTool>> "%log%"
echo NOTE: through winget, which is the supported way to have it now.>> "%log%"
echo ExifTool not bundled; the installer offers it through winget.
:exifToolDone

rem ---- JSON -----------------------------------------------------------
rem No JSON package is fetched, because none is needed. HomerScribe reads and
rem writes JSON with JavaScriptSerializer from System.Web.Extensions, which is
rem part of the .NET Framework itself. DbDo pulls in Newtonsoft.Json because it
rem needs what Newtonsoft does that the built-in serializer cannot; nothing here
rem does. Keeping to the built-in one is also what keeps HomerScribe.exe a
rem single self-contained file, with no DLL beside it.

rem ---- documentation ---------------------------------------------------
rem The .htm files are built alongside the .md files and shipped with them, so
rem there is nothing to generate here. no converter is consulted: the one that used to be
rem reported its own absence on every build and did nothing when present.

rem ---- the Homer Development Kit ---------------------------------------
rem HomerScribe no longer carries its own copies of the Homer classes. They
rem live in one place, so a fix reaches every app that uses them, and so the
rem version HomerScribe compiles against is a fact rather than a guess.
rem
rem That mattered here: the copies of Inix.cs, Lbc.cs, Say.cs and Web.cs in
rem this folder had all drifted from the kit's, and PdfRead.cs — written for
rem HomerScribe and since promoted into the kit — was byte for byte the same,
rem which is the good case and still one file too many.
rem
rem Looked for in order: the HomerDev environment variable, C:\HomerDev, then
rem this folder.
set "homerDev="
if defined HomerDev if exist "%HomerDev%\CSharp\Lbc.cs" set "homerDev=%HomerDev%"
if not defined homerDev if exist "C:\HomerDev\CSharp\Lbc.cs" set "homerDev=C:\HomerDev"
if not defined homerDev if exist "%CD%\CSharp\Lbc.cs" set "homerDev=%CD%"
if not defined homerDev (
  echo ERROR: The Homer Development Kit was not found.
  echo Unzip it into C:\HomerDev, or set the HomerDev environment variable.
  echo ERROR: kit not found >> "%log%"
  exit /b 1
)
set "homerVer=unknown"
rem READ WITH POWERSHELL, NOT set /p: on 25 Sep 2026 version.txt carried a byte
rem order mark, set /p handed the three BOM bytes to the [version] cast, and the
rem build refused a kit of exactly the version it asked for. Get-Content with
rem -Encoding UTF8 drops a BOM; Trim drops spaces and line ends.
if exist "!homerDev!\version.txt" for /f "usebackq delims=" %%V in (`powershell -NoProfile -Command "(Get-Content -Raw -Encoding UTF8 '!homerDev!\version.txt').Trim([char]0xFEFF).Trim()"`) do set "homerVer=%%V"
echo Kit: !homerDev! version !homerVer! >> "%log%"
echo Kit: !homerDev! version !homerVer!

rem THE KIT MUST BE NEW ENOUGH FOR THE SOURCE. HomerScribe.cs uses what the kit
rem gives it, and a kit older than the source fails deep in the compiler with a
rem message naming the symptom and not the cause. So the build says the cause.
rem 1.30.0 adds homerOutcomeLine for the Results box; 1.29.0 put the kit files in Templates\, where the
rem installer includes the first from; an older kit has them elsewhere or not at all.
rem An older kit compiles the C# and then fails the installer with "Invalid
rem number of parameters" -- which is what happened when HomerDev.zip was
rem delivered but not unpacked. Failing here says what is wrong.
set "kitNeeded=1.38.1"
powershell -NoProfile -Command "if ([version]'!homerVer!' -lt [version]'!kitNeeded!') { exit 1 } else { exit 0 }" >nul 2>&1
if errorlevel 1 (
  echo ERROR: HomerScribe needs HomerDev !kitNeeded! or later, and the kit is !homerVer!. >> "%log%"
  echo(
  echo HomerScribe needs HomerDev !kitNeeded! or later, and the kit is !homerVer!.
  echo Unzip HomerDev.zip into C:\HomerDev, then build again.
  exit /b 1
)

rem The modules HomerScribe uses. PdfRead needs nothing else; Inix reads and
rem writes .xlsx, so the compression assembly is referenced below.
set "homerSources="
set "homerSources=!homerSources! "!homerDev!\CSharp\Elevate.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Inix.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Lbc.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Log.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Ollama.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Paths.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\PdfRead.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Say.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Util.cs""
set "homerSources=!homerSources! "!homerDev!\CSharp\Web.cs""
echo Homer modules: !homerSources! >> "%log%"

rem ---- the context examples live in templates now -----------------------
rem A folder named context shared its first letter with configs, and the
rem standard folders carry distinct first letters. What was there -- the
rem worked examples of a context file, which a person copies and edits --
rem moves into templates, once, and the empty folder goes.
if exist "context" (
  if not exist "templates" mkdir "templates"
  for %%F in (context\*.md context\*.htm) do (
    if exist "%%F" (
      move /y "%%F" "templates\" >nul
      echo Moved %%F to templates\>> "%log%"
    )
  )
  rd "context" 2>nul && echo Removed the empty context folder.>> "%log%"
  if exist "context" echo WARN: context\ still holds something that is not .md or .htm; look and move it by hand.
)

rem ---- tutorials: spoken when their audio is missing -------------------
rem The scripts are help\Tutorial_*.inix; the audio is help\tutorials\<name>.mp3,
rem one file per walk, with Tutorials.m3u beside them. The three tools that
rem make them -- buildTutorials.cmd, buildTutorials.ps1, makeTutorials.py --
rem are the kit's, refreshed into scripts\ on every build so there is one
rem source of truth and the app still carries what it needs. Speaking happens
rem only when a walk has no audio yet: delete an .mp3 to have it spoken again.
rem The voices live in C:\HomerDev\exec, fetched by buildHomerDev alone; when they are
rem missing, the tool says to run buildHomerDev and speaks nothing.
rem THE KIT'S TOOLS THE APP CARRIES, refreshed on every build so there is one
rem source of truth: the tutorial tools, homerTidy, and the release tools --
rem tagRelease (tag, push, publish the installer), gitPush (commit and push with a message), gitUnpushed
rem (undo commits not yet pushed, keeping every file). Run them from the
rem project folder: scripts\tagRelease, scripts\homerTidy --do-it, and so on.
if exist "!homerDev!\scripts\buildTutorials.ps1" (
  for %%F in (homerInstall.cmd installOllama.cmd buildTutorials.cmd buildTutorials.ps1 checkTutorial.cmd checkTutorial.py makeTutorials.py homerTidy.cmd homerTidy.py checkHomerApp.cmd checkHomerApp.py tagRelease.cmd tagRelease.ps1 gitPush.cmd gitUnpushed.cmd gitUnpushed.py) do (
    if exist "!homerDev!\scripts\%%F" copy /y "!homerDev!\scripts\%%F" scripts\ >nul
  )
  echo Kit tools refreshed into scripts\.>> "%log%"
)
rem Retired kit scripts an app may still carry from an earlier refresh: gone.
for %%F in (cleanDir.cmd cleanDir.py gitRelease.cmd homerPolicy.py installTools.cmd sayTutorial.cmd sayTutorial.py tidyRepo.cmd tidyRepo.py) do (
  if exist "scripts\%%F" del /q "scripts\%%F" && echo Removed retired scripts\%%F>> "%log%"
)
set "tutorialsMissing="
for %%F in (help\Tutorial_*.inix) do if not exist "help\tutorials\%%~nF.mp3" set "tutorialsMissing=1"
if defined tutorialsMissing (
  echo Speaking the tutorials that have no audio yet, with the voices in C:\HomerDev\exec.
  echo ---- tutorials ---->> "%log%"
  rem THE TOOL'S OWN LINES GO TO THE SCREEN, NOT INTO THIS LOG. It names each
  rem tutorial as it starts and as it finishes, and a few minutes of silence
  rem between those two lines is speaking, not downloading. It keeps its own
  rem log in logs\; this log gets the outcome.
  rem -build: an argument of its own, because a bare call hands the tool THIS
  rem script's arguments through %* (a cmd quirk): "nobump" arrived as a script name.
  call "scripts\buildTutorials.cmd" -build
  if errorlevel 1 (
    echo WARN: not every tutorial could be spoken. The tutorials log in logs\ says why.
    echo WARN: not every tutorial could be spoken.>> "%log%"
  ) else (
    echo Tutorials spoken.>> "%log%"
  )
) else (
  echo Tutorials: every walk already has its audio.>> "%log%"
)


rem ---- PdfPig, found or fetched ---------------------------------------
rem HomerScribe reads PDFs and PdfPig (Apache 2.0) is what lets it.
rem
rem THE WORK IS IN getPdfPig.ps1, A FILE SHIPPED BESIDE THIS ONE, and that is
rem the point. Earlier versions carried the PowerShell inline -- first with
rem caret continuations, then written line by line with echo, then base64'd
rem into -EncodedCommand -- and every one of those was edited afterwards by
rem string replacement with no way to check the result. One such edit left
rem   $pkg = Join-Path $PWD 'packages''
rem with a trailing quote, and the whole fetch died on it.
rem
rem A plain .ps1 can be read, diffed and checked before it ships. Nothing is
rem encoded and nothing is patched.

echo Fetching PdfPig if needed>> "%log%"
where nuget >nul 2>&1
if not errorlevel 1 (
  echo   asking nuget for PdfPig and its dependencies>> "%log%"
  nuget install PdfPig -OutputDirectory packages -ExcludeVersion -NonInteractive -DependencyVersion Highest >> "%log%" 2>&1
)

if exist "scripts\getPdfPig.ps1" (
  powershell -NoProfile -ExecutionPolicy Bypass -File "scripts\getPdfPig.ps1" >> "%log%" 2>&1
) else (
  echo ERROR: getPdfPig.ps1 is missing from this folder.>> "%log%"
)

set "pdfDll="
if exist "pdfpig.name" set /p pdfDll=<pdfpig.name
if not defined pdfDll (
  echo(
  echo ERROR: PdfPig could not be found or fetched. The log says what was tried:
  echo %log%
  echo PdfPig could not be found or fetched>> "%log%"
  goto :failed
)
if not exist "%pdfDll%" (
  echo(
  echo ERROR: %pdfDll% was named but is not here. The log says what happened:
  echo %log%
  echo %pdfDll% was named but is absent>> "%log%"
  goto :failed
)

rem Every assembly the package brought, plus the ones its .NET Framework build
rem needs for Span and ReadOnlyMemory.
set "pdfRefs="
for %%F in (*PdfPig*.dll) do set pdfRefs=!pdfRefs! /reference:"%%~fF"
for %%F in (System.Memory.dll System.Buffers.dll System.Runtime.CompilerServices.Unsafe.dll System.Numerics.Vectors.dll System.Threading.Tasks.Extensions.dll System.ValueTuple.dll) do if exist "%%F" set pdfRefs=!pdfRefs! /reference:"%CD%\%%F"
rem The runtime needs the binding redirects too, not just the compiler's
rem assumption. Without HomerScribe.exe.config beside the executable, PdfPig
rem asks for System.Memory 4.0.2.0, finds 4.0.5.0, and throws on the first PDF.
rem The config must not merely exist: it must name the version of System.Memory
rem that is actually here. A config left by an earlier build redirected to
rem 4.0.2.0 while 4.0.5.0 sat beside it, and HomerScribe threw on the first
rem PDF. Checking presence alone let that through twice.
if not exist "HomerScribe.exe.config" (
  echo ERROR: HomerScribe.exe.config was not written. PDFs would fail at run time.
  echo HomerScribe.exe.config is missing>> "%log%"
  goto :failed
)
if exist "scripts\checkConfig.ps1" powershell -NoProfile -ExecutionPolicy Bypass -File "scripts\checkConfig.ps1" >> "%log%" 2>&1
if errorlevel 1 (
  echo ERROR: the binding redirects do not match the assemblies present.
  echo See %log%.
  goto :failed
)
echo PdfPig ready: %pdfDll%>> "%log%"
echo References: !pdfRefs!>> "%log%"

rem ---- optional icon ------------------------------------------------
set "icon="
if exist "%app%.ico" set "icon=/win32icon:%app%.ico"
if defined icon echo Icon: %app%.ico>> "%log%"

rem ---- is the program still running? ---------------------------------
rem The compiler cannot replace an executable that is open, and its message for
rem that -- CS2012, "used by another process" -- reads like a fault in the code
rem when it is nothing of the kind.
rem
rem Renaming the file was the old test, and it does not work: Windows allows a
rem RUNNING executable to be renamed, because a handle refers to the file and
rem not to its name. The rename succeeded every time and the check never fired.
rem
rem Two tests instead. Ask Windows whether the process is running, and try to
rem open the file for writing, which is what the compiler is about to do and the
rem only question that really matters.

if not exist "%app%.exe" goto :notRunning

rem Can THIS file be written? That is the only question, and it is the same
rem operation the compiler is about to attempt. A HomerScribe running from
rem another folder is a different file and no obstacle at all.
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "try { $f=[IO.File]::Open('%cd%\%app%.exe','Open','Write','None'); $f.Close(); exit 0 } catch { exit 1 }" >nul 2>&1
if not errorlevel 1 goto :notRunning

rem It cannot. Is a HomerScribe running, so the message can say which case it is?
tasklist /fi "imagename eq %app%.exe" /nh 2>nul | find /i "%app%.exe" >nul
if not errorlevel 1 goto :stillRunning
goto :lockedByOther

:stillRunning
echo(
echo ERROR: %app%.exe is running, so the compiler cannot replace it.
echo(
echo Close %app% and run this again. If no window is open, a run may have been
echo left behind; end it with
echo     taskkill /im %app%.exe /f
echo(
echo To build WITHOUT stopping a run, unpack the source into another folder and
echo build there. The file being written is then a different file, and the two
echo do not interfere.
echo(
echo ERROR: %app%.exe is running, found by tasklist.>> "%log%"
goto :failed

:lockedByOther
echo(
echo ERROR: %app%.exe cannot be opened for writing, so the compiler cannot
echo replace it. No process of that name is running, so something else holds
echo the file: an antivirus scan, an Explorer preview, or a debugger.
echo Wait a moment and run this again.
echo(
echo ERROR: %app%.exe is locked, though no process of that name is running.>> "%log%"
goto :failed

:notRunning

rem ---- compile ------------------------------------------------------
rem Seven sources compiled together into ONE assembly, so the result is
rem still a single self-contained executable:
rem   Version.cs        -- generated from version.txt
rem   HomerScribe.cs  -- the program
rem   the Homer classes -- compiled from C:\HomerDev\CSharp, not from here
rem
rem THIS LINE WAS DELETED BY AN EDIT OF MINE AND NOT REPLACED. The script went
rem on finding the compiler, checking the exe was not locked, reporting "Built
rem HomerScribe.exe", and never compiling anything -- so every build since
rem produced no new executable, and he kept running the same old one while I
rem kept explaining why my changes should have taken effect. The version stayed
rem at 1.0.237 in every log he sent, which was the evidence, in front of me,
rem every time.
"!csc!" /nologo /target:winexe /platform:x64 /out:"%app%.exe" ^
  /reference:"!speech!" /reference:"!uiaProv!" /reference:"!uiaTypes!" ^
  /reference:"System.IO.Compression.dll" /reference:"System.IO.Compression.FileSystem.dll" ^
  /reference:"Microsoft.VisualBasic.dll" ^
  !pdfRefs! ^
  Version.cs %app%.cs !homerSources! >> "%log%" 2>&1
set iBuildResult=%ERRORLEVEL%
type "%log%"
if not "%iBuildResult%"=="0" (
  echo(
  echo ERROR: the build failed. Details above and in %log%.
  goto :failed
)
rem PdfPig.dll goes beside the executable, because it is referenced rather
rem than embedded. HomerScribe was never going to be one self-contained file
rem anyway -- it leans on Ollama, Whisper, ffmpeg and ExifTool -- so a DLL on
rem disk is the simpler and more reliable arrangement: the runtime loads it by
rem path, with its identity and version intact, instead of from a byte array.
if exist "%pdfDll%" (
  echo %pdfDll% is beside the executable.>> "%log%"
)
rem THE FILE, NOT THE EXIT CODE, AND ITS AGE. A build that compiles nothing
rem once reported "Built HomerScribe.exe" for a week while the exe on disk was
rem untouched. So: it must exist, and it must have been written just now.
if not exist "%app%.exe" (
  echo(
  echo ERROR: %app%.exe was not produced. Nothing was compiled.
  echo ERROR: %app%.exe does not exist after the compile step.>> "%log%"
  goto :failed
)
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$f=Get-Item '%cd%\%app%.exe'; if (((Get-Date) - $f.LastWriteTime).TotalMinutes -gt 5) { exit 1 } else { exit 0 }" >nul 2>&1
if errorlevel 1 (
  echo(
  echo ERROR: %app%.exe is older than this build, so nothing was compiled.
  echo ERROR: %app%.exe was not rewritten by this build.>> "%log%"
  goto :failed
)
echo Built %app%.exe version !ver!>> "%log%"
echo(
echo Built %app%.exe version !ver!

rem ---- installer, if Inno Setup is present --------------------------
set "iscc="
if exist "!progFiles86!\Inno Setup 6\ISCC.exe" set "iscc=!progFiles86!\Inno Setup 6\ISCC.exe"
if not defined iscc if exist "!progFiles!\Inno Setup 6\ISCC.exe" set "iscc=!progFiles!\Inno Setup 6\ISCC.exe"
if not defined iscc (
  echo Inno Setup was not found, so no installer was built.>> "%log%"
  echo(
  echo Inno Setup was not found. To produce %app%_setup.exe, open
  echo %app%_setup.iss in Inno Setup and click Compile.
  goto :done
)
echo Inno Setup: !iscc!>> "%log%"
"!iscc!" "%app%_setup.iss" >> "%log%" 2>&1
if errorlevel 1 (
  echo ERROR: the installer build failed. See %log%.
  echo ERROR: the installer build failed.>> "%log%"
  goto :failed
)
echo Built %app%_setup.exe version !ver!>> "%log%"
echo Built %app%_setup.exe version !ver!

:done
echo Build succeeded %DATE% %TIME%>> "%log%"
echo(
echo To publish: commit, then run tagRelease. It reads the version from
echo the version resource of %app%_setup.exe and tags v!ver!.
endlocal
exit /b 0

:failed
echo Build FAILED %DATE% %TIME%>> "%log%"
endlocal
exit /b 1

:takeNextVersion
rem -------------------------------------------------------------------
rem Take the next UNUSED version. The last dotted part of !ver! is
rem incremented, and any number that already carries a release tag on
rem the origin remote is stepped over, so a version.txt that has fallen
rem behind the repository cannot mint a number that is already spent.
rem That is what happened on 17 August 2026: version.txt held 1.0.143
rem while 1.0.144 was already released, the build stamped a second
rem 1.0.144, and tagRelease refused it at the end of the work.
rem
rem One "git ls-remote" is the only network call the build makes. If it
rem fails, the plain increment is used and tagRelease remains the check
rem it has always been, so a machine with no network still builds.
rem
rem These are subroutines rather than parenthesised blocks, so each line
rem is parsed on its own.
rem -------------------------------------------------------------------
set "verOld=!ver!"
set "sTagFile=%TEMP%\%app%_tags.txt"
del "!sTagFile!" >nul 2>&1
git ls-remote --tags origin "v*" > "!sTagFile!" 2>> "%log%"
if errorlevel 1 echo WARN: the released tags could not be read, so the next number is taken blindly.>> "%log%"
if errorlevel 1 del "!sTagFile!" >nul 2>&1

:nextCandidate
call :incrementVersion
if not defined new goto :eof
if not exist "!sTagFile!" goto :haveNextVersion
findstr /e /c:"refs/tags/v!ver!" "!sTagFile!" >nul 2>&1
if errorlevel 1 goto :haveNextVersion
echo Version v!ver! is already released; stepping over it.
echo Version v!ver! is already released; stepping over it.>> "%log%"
goto :nextCandidate

:haveNextVersion
del "!sTagFile!" >nul 2>&1
> version.txt echo !ver!
echo Version: !verOld! -^> !ver!
echo Version: !verOld! -^> !ver!>> "%log%"
goto :eof

:incrementVersion
rem -------------------------------------------------------------------
rem Increment the last dotted part of !ver!. Nothing is written here, so
rem the caller may call this repeatedly while stepping over numbers that
rem are already spent.
rem -------------------------------------------------------------------
set "p1=" & set "p2=" & set "p3=" & set "p4="
set "new="
for /f "tokens=1-4 delims=." %%a in ("!ver!") do (
  set "p1=%%a" & set "p2=%%b" & set "p3=%%c" & set "p4=%%d"
)
if defined p4 (
  set /a p4=p4+1
  set "new=!p1!.!p2!.!p3!.!p4!"
) else if defined p3 (
  set /a p3=p3+1
  set "new=!p1!.!p2!.!p3!"
) else if defined p2 (
  set "new=!p1!.!p2!.1"
) else (
  set "new=!p1!.0.1"
)
if not defined new (
  echo ERROR: could not work out the next version from "!ver!".
  echo ERROR: could not work out the next version from "!ver!".>> "%log%"
  goto :eof
)
set "ver=!new!"
goto :eof


rem ---- is this ExifTool new enough? --------------------------------------
rem Sets exifVer and exifOk. Called with the path to an exiftool.exe.
rem A version is "11.79" or "13.59"; comparing them as numbers goes wrong at
rem 11.9 against 11.79, so they are compared as version objects.
:exifToolOldEnough
set "exifVer="
set "exifOk=no"
if not exist %1 goto :eof
for /f "usebackq delims=" %%v in (`%1 -ver 2^>nul`) do set "exifVer=%%v"
if not defined exifVer goto :eof
for /f "usebackq delims=" %%o in (`powershell -NoProfile -Command ^
  "try { if ([version]('%exifVer%' + '.0') -ge [version]('%exifWant%' + '.0')) { 'yes' } else { 'no' } } catch { 'no' }"`) do set "exifOk=%%o"
goto :eof

rem ---- is there a single-file exiftool.exe in this folder? ----------------
rem Sets haveExif if the folder holds an exiftool.exe that RUNS and has no
rem "exiftool_files" beside it. A folder beside the exe disqualifies it,
rem whatever its version, because Jamal wants one file and nothing else.
:exifToolTrySingle
if defined haveExif goto :eof
if "%~1"=="" goto :eof
if not exist "%~1\exiftool.exe" goto :eof
if exist "%~1\exiftool_files" (
  echo Passing over %~1: it needs an exiftool_files folder beside it.>> "%log%"
  goto :eof
)
call :exifToolOldEnough "%~1\exiftool.exe"
if not defined exifVer goto :eof
set "haveExif=%~1"
goto :eof
