@echo off
rem ===================================================================
rem buildHomerDescribe.cmd -- build HomerDescribe.exe.
rem
rem Follows the pattern proven by buildDbDo.cmd and buildUrlFido.cmd.
rem
rem VERSION: version.txt is the SINGLE source of truth. It holds one
rem line, nothing else. This script increments it on every build, then
rem generates Version.cs from it, so the running program reports the
rem same number. HomerDescribe_setup.iss reads version.txt directly, so
rem the installer reports it too, and tagRelease reads it back out of
rem the built setup's version resource to form the tag. No version
rem literal appears anywhere else, so a stale file cannot rewind it.
rem
rem   buildHomerDescribe.cmd          increments the version, then builds
rem   buildHomerDescribe.cmd nobump   keeps the current number
rem
rem COMPILER: Roslyn is preferred, from Visual Studio or the free Build
rem Tools. The pre-Roslyn csc.exe under Microsoft.NET\Framework64 is
rem accepted as a fallback, since HomerDescribe.cs uses no language
rem feature beyond C# 5. The Homer modules do, so if the fallback is
rem used and Lbc.cs or Say.cs fails to compile, install Build Tools:
rem https://visualstudio.microsoft.com/downloads/
rem
rem REFERENCES: three assemblies are NOT on the compiler's default
rem reference path and must be given by full path, or the build fails
rem with CS0006:
rem   System.Speech.dll        -- the Windows voices
rem   UIAutomationProvider.dll -- Say.cs, Narrator notification events
rem   UIAutomationTypes.dll    -- Say.cs
rem
rem PARSE-TIME PITFALL: the variable NAME ProgramFiles(x86) contains
rem parentheses, and cmd.exe scans a parenthesised block for its closing
rem paren BEFORE expanding variables. Every search below is therefore a
rem single-line "if not defined X if exist ... set" chain, never a block.
rem
rem Output in this folder: HomerDescribe.exe, and the installer if Inno
rem Setup is present. Everything is logged to buildHomerDescribe.log.
rem ===================================================================

setlocal enabledelayedexpansion
cd /d "%~dp0"

set "app=HomerDescribe"
set "log=%CD%\buildHomerDescribe.log"
echo %app% build started %DATE% %TIME%> "%log%"
echo Script: %~f0>> "%log%"
echo Folder: %CD%>> "%log%"
echo Command line: %0 %*>> "%log%"
echo Build log: %log%

rem ---- version: version.txt is the single source of truth -----------
if not exist "version.txt" (
  echo ERROR: version.txt not found. It must hold the current version, e.g. 1.0.0
  echo ERROR: version.txt not found.>> "%log%"
  goto :failed
)
set "ver="
set /p ver=<version.txt
set "ver=!ver: =!"
if "!ver!"=="" (
  echo ERROR: version.txt is empty.
  echo ERROR: version.txt is empty.>> "%log%"
  goto :failed
)
if /i "%~1"=="nobump" goto :keepVersion
call :takeNextVersion
goto :haveVersion

:keepVersion
echo Version: !ver! ^(nobump: keeping the current number^)
echo Version: !ver! ^(nobump^)>> "%log%"

:haveVersion

rem ---- generate Version.cs from version.txt -------------------------
rem Generated output: do not edit it, and do not commit it.
> Version.cs echo // Generated by buildHomerDescribe.cmd from version.txt.  Do not edit; do not commit.
>> Version.cs echo public static class BuildVersion
>> Version.cs echo {
>> Version.cs echo     public const string Version = "!ver!";
>> Version.cs echo }
echo Wrote Version.cs for !ver!>> "%log%"

rem ---- locate the compiler ------------------------------------------
set "csc="
if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe" set "csc=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Roslyn\csc.exe"
if not defined csc if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe" set "csc=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\csc.exe"
if not defined csc (
  echo ERROR: no C# compiler was found.
  echo ERROR: no C# compiler was found.>> "%log%"
  goto :failed
)
echo Compiler: !csc!
echo Compiler: !csc!>> "%log%"

rem ---- locate the reference assemblies given by full path -----------
rem Copy the paren-bearing root into a paren-free name before any block.
set "progFiles86=%ProgramFiles(x86)%"
set "progFiles=%ProgramFiles%"
set "refBase=Reference Assemblies\Microsoft\Framework\.NETFramework"

set "speech="
set "uiaProv="
set "uiaTypes="

for %%v in (v4.8 v4.7.2 v4.7.1 v4.7 v4.6.2 v4.6.1 v4.6 v4.5.2) do (
  if not defined speech if exist "!progFiles86!\!refBase!\%%v\System.Speech.dll" set "speech=!progFiles86!\!refBase!\%%v\System.Speech.dll"
  if not defined speech if exist "!progFiles!\!refBase!\%%v\System.Speech.dll" set "speech=!progFiles!\!refBase!\%%v\System.Speech.dll"
  if not defined uiaProv if exist "!progFiles86!\!refBase!\%%v\UIAutomationProvider.dll" set "uiaProv=!progFiles86!\!refBase!\%%v\UIAutomationProvider.dll"
  if not defined uiaProv if exist "!progFiles!\!refBase!\%%v\UIAutomationProvider.dll" set "uiaProv=!progFiles!\!refBase!\%%v\UIAutomationProvider.dll"
  if not defined uiaTypes if exist "!progFiles86!\!refBase!\%%v\UIAutomationTypes.dll" set "uiaTypes=!progFiles86!\!refBase!\%%v\UIAutomationTypes.dll"
  if not defined uiaTypes if exist "!progFiles!\!refBase!\%%v\UIAutomationTypes.dll" set "uiaTypes=!progFiles!\!refBase!\%%v\UIAutomationTypes.dll"
)

rem Fallbacks: the assembly cache and the runtime WPF folder.
if not defined speech if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\System.Speech\v4.0_4.0.0.0__31bf3856ad364e35\System.Speech.dll" set "speech=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\System.Speech\v4.0_4.0.0.0__31bf3856ad364e35\System.Speech.dll"
if not defined uiaProv if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationProvider.dll" set "uiaProv=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationProvider.dll"
if not defined uiaTypes if exist "%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationTypes.dll" set "uiaTypes=%SystemRoot%\Microsoft.NET\Framework64\v4.0.30319\WPF\UIAutomationTypes.dll"
if not defined uiaProv if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll" set "uiaProv=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationProvider\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationProvider.dll"
if not defined uiaTypes if exist "%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll" set "uiaTypes=%SystemRoot%\Microsoft.NET\assembly\GAC_MSIL\UIAutomationTypes\v4.0_4.0.0.0__31bf3856ad364e35\UIAutomationTypes.dll"

if not defined speech (
  echo ERROR: System.Speech.dll was not found.
  echo         Install the .NET Framework 4.8 Developer Pack:
  echo         https://dotnet.microsoft.com/download/dotnet-framework/net48
  echo ERROR: System.Speech.dll was not found.>> "%log%"
  goto :failed
)
if not defined uiaProv (
  echo ERROR: UIAutomationProvider.dll was not found. Install the .NET Framework 4.8 Developer Pack.
  echo ERROR: UIAutomationProvider.dll was not found.>> "%log%"
  goto :failed
)
if not defined uiaTypes (
  echo ERROR: UIAutomationTypes.dll was not found. Install the .NET Framework 4.8 Developer Pack.
  echo ERROR: UIAutomationTypes.dll was not found.>> "%log%"
  goto :failed
)
echo Speech: !speech!>> "%log%"
echo UI Automation: !uiaProv!>> "%log%"

rem ---- the installer's helper scripts --------------------------------
if not exist "installOllama.cmd" echo WARN: installOllama.cmd is missing; the installer's Ollama checkbox will not work.>> "%log%"
if not exist "installModels.cmd" echo WARN: installModels.cmd is missing; the installer's model checkbox will not work.>> "%log%"
if not exist "context\*.md" echo NOTE: the context folder holds no .md example. The installer skips it.>> "%log%"

rem ---- the companion programs the installer packages -------------------
rem ffmpeg does the video and audio work; yt-dlp fetches video from a web
rem address. Neither is committed to the repository -- ffmpeg alone is far past
rem what a repository should carry -- so they are fetched here when missing.
rem The downloads are idempotent: a file already present is left alone.
rem
rem ffmpeg comes from BtbN's LGPL build rather than a GPL one. Both work
rem identically here, and the LGPL build carries lighter obligations when the
rem installer is redistributed. See License.md.

if exist "ffmpeg.exe" if exist "ffprobe.exe" goto :haveFfmpeg
echo Fetching ffmpeg and ffprobe. This is a large download and happens once.
echo Fetching ffmpeg and ffprobe>> "%log%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;" ^
  "$url = 'https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-master-latest-win64-lgpl.zip';" ^
  "$tmpZip = Join-Path $env:TEMP 'homerFfmpeg.zip';" ^
  "$tmpDir = Join-Path $env:TEMP 'homerFfmpeg';" ^
  "if (Test-Path $tmpZip) { Remove-Item -Force $tmpZip };" ^
  "if (Test-Path $tmpDir) { Remove-Item -Recurse -Force $tmpDir };" ^
  "Invoke-WebRequest -Uri $url -OutFile $tmpZip -UseBasicParsing;" ^
  "Expand-Archive -Path $tmpZip -DestinationPath $tmpDir;" ^
  "foreach ($name in @('ffmpeg.exe','ffprobe.exe')) {" ^
  "  $item = Get-ChildItem -Path $tmpDir -Recurse -Filter $name;" ^
  "  if ($item -is [array]) { $item = $item[0] };" ^
  "  $found = $null; if ($item -ne $null) { $found = $item.FullName };" ^
  "  if ($null -eq $found) { throw ($name + ' was not in the archive') };" ^
  "  Copy-Item -Path $found -Destination $name -Force;" ^
  "}" ^
  "Remove-Item -Force $tmpZip;" ^
  "Remove-Item -Recurse -Force $tmpDir;" >> "%log%" 2>&1
if errorlevel 1 (
  echo WARNING: ffmpeg could not be downloaded; see %log%.
  echo WARNING: ffmpeg could not be downloaded.>> "%log%"
  echo To fix by hand, download a win64 build from https://ffmpeg.org/download.html
  echo and copy ffmpeg.exe and ffprobe.exe into this folder.
)
:haveFfmpeg
if exist "ffmpeg.exe" echo ffmpeg.exe is present>> "%log%"
if not exist "ffmpeg.exe" echo WARN: ffmpeg.exe is absent; the installer will not package it.>> "%log%"

if exist "yt-dlp.exe" goto :haveYtDlp
echo Fetching yt-dlp.
echo Fetching yt-dlp>> "%log%"
powershell -NoProfile -ExecutionPolicy Bypass -Command ^
  "$ErrorActionPreference='Stop';" ^
  "[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12;" ^
  "$url = 'https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp.exe';" ^
  "Invoke-WebRequest -Uri $url -OutFile 'yt-dlp.exe' -UseBasicParsing;" >> "%log%" 2>&1
if errorlevel 1 (
  echo WARNING: yt-dlp could not be downloaded; see %log%.
  echo WARNING: yt-dlp could not be downloaded.>> "%log%"
  echo To fix by hand, download yt-dlp.exe from
  echo   https://github.com/yt-dlp/yt-dlp/releases/latest
  echo and copy it into this folder.
)
:haveYtDlp
if exist "yt-dlp.exe" echo yt-dlp.exe is present>> "%log%"

rem ---- JSON -----------------------------------------------------------
rem No JSON package is fetched, because none is needed. HomerDescribe reads and
rem writes JSON with JavaScriptSerializer from System.Web.Extensions, which is
rem part of the .NET Framework itself. DbDo pulls in Newtonsoft.Json because it
rem needs what Newtonsoft does that the built-in serializer cannot; nothing here
rem does. Keeping to the built-in one is also what keeps HomerDescribe.exe a
rem single self-contained file, with no DLL beside it.

rem ---- documentation in both forms ------------------------------------
rem The .md files are the source; the .htm files are what the shortcuts open.
rem 2htm, another of the Homer Tools, does the conversion when it is on the
rem PATH or beside this script. When it is not, whatever .htm files are already
rem here are packaged unchanged, so the build never fails over documentation.
set "twohtm="
if exist "2htm.exe" set "twohtm=2htm.exe"
if not defined twohtm where 2htm.exe >nul 2>&1
if not defined twohtm if not errorlevel 1 set "twohtm=2htm.exe"
if not defined twohtm echo NOTE: 2htm was not found, so the .htm documentation was not regenerated.>> "%log%"
if defined twohtm echo Regenerating the .htm documentation with %twohtm%>> "%log%"
if defined twohtm "%twohtm%" -f ReadMe.md >> "%log%" 2>&1
if defined twohtm "%twohtm%" -f History.md >> "%log%" 2>&1
if defined twohtm "%twohtm%" -f License.md >> "%log%" 2>&1

rem ---- optional icon ------------------------------------------------
set "icon="
if exist "%app%.ico" set "icon=/win32icon:%app%.ico"
if defined icon echo Icon: %app%.ico>> "%log%"

rem ---- compile ------------------------------------------------------
rem Seven sources compiled together into ONE assembly, so the result is
rem still a single self-contained executable:
rem   Version.cs        -- generated from version.txt
rem   HomerDescribe.cs  -- the program
rem   Lbc.cs            -- Homer layout-by-code dialogs
rem   Say.cs            -- Homer screen-reader announcements
rem   Inix.cs           -- Homer ini codec and input history
rem   Util.cs           -- Homer general utilities
rem   Web.cs            -- Homer web helpers
echo Compiling>> "%log%"
echo(>> "%log%"
"!csc!" /nologo /target:exe /platform:x64 /optimize+ ^
  /reference:System.dll ^
  /reference:System.Core.dll ^
  /reference:System.Data.dll ^
  /reference:System.Drawing.dll ^
  /reference:System.Windows.Forms.dll ^
  /reference:System.Web.dll ^
  /reference:System.Web.Extensions.dll ^
  /reference:System.Net.Http.dll ^
  /reference:System.Xml.dll ^
  /reference:Microsoft.VisualBasic.dll ^
  /reference:"!speech!" ^
  /reference:"!uiaProv!" ^
  /reference:"!uiaTypes!" ^
  !icon! ^
  /out:%app%.exe ^
  Version.cs %app%.cs Lbc.cs Say.cs Inix.cs Util.cs Web.cs >> "%log%" 2>&1

set iBuildResult=%ERRORLEVEL%
type "%log%"
if not "%iBuildResult%"=="0" (
  echo(
  echo ERROR: the build failed. Details above and in %log%.
  goto :failed
)
echo Built %app%.exe version !ver!>> "%log%"
echo(
echo Built %app%.exe version !ver!

rem ---- installer, if Inno Setup is present --------------------------
set "iscc="
if exist "!progFiles86!\Inno Setup 6\ISCC.exe" set "iscc=!progFiles86!\Inno Setup 6\ISCC.exe"
if not defined iscc if exist "!progFiles!\Inno Setup 6\ISCC.exe" set "iscc=!progFiles!\Inno Setup 6\ISCC.exe"
if not defined iscc (
  echo Inno Setup was not found, so no installer was built.>> "%log%"
  echo(
  echo Inno Setup was not found. To produce %app%_setup.exe, open
  echo %app%_setup.iss in Inno Setup and click Compile.
  goto :done
)
echo Inno Setup: !iscc!>> "%log%"
"!iscc!" "%app%_setup.iss" >> "%log%" 2>&1
if errorlevel 1 (
  echo ERROR: the installer build failed. See %log%.
  echo ERROR: the installer build failed.>> "%log%"
  goto :failed
)
echo Built %app%_setup.exe version !ver!>> "%log%"
echo Built %app%_setup.exe version !ver!

:done
echo Build succeeded %DATE% %TIME%>> "%log%"
echo(
echo To publish: commit, then run tagRelease. It reads the version from
echo the version resource of %app%_setup.exe and tags v!ver!.
endlocal
exit /b 0

:failed
echo Build FAILED %DATE% %TIME%>> "%log%"
endlocal
exit /b 1

:takeNextVersion
rem -------------------------------------------------------------------
rem Take the next version: increment the last dotted part of !ver!.
rem No network call is made; tagRelease does the "already released"
rem check, which is where a stall would be visible and interruptible.
rem This is a subroutine rather than a parenthesised block, so each line
rem is parsed on its own.
rem -------------------------------------------------------------------
set "p1=" & set "p2=" & set "p3=" & set "p4="
set "new="
for /f "tokens=1-4 delims=." %%a in ("!ver!") do (
  set "p1=%%a" & set "p2=%%b" & set "p3=%%c" & set "p4=%%d"
)
if defined p4 (
  set /a p4=p4+1
  set "new=!p1!.!p2!.!p3!.!p4!"
) else if defined p3 (
  set /a p3=p3+1
  set "new=!p1!.!p2!.!p3!"
) else if defined p2 (
  set "new=!p1!.!p2!.1"
) else (
  set "new=!p1!.0.1"
)
if not defined new (
  echo ERROR: could not work out the next version from "!ver!".
  echo ERROR: could not work out the next version from "!ver!".>> "%log%"
  goto :eof
)
> version.txt echo !new!
echo Version: !ver! -^> !new!
echo Version: !ver! -^> !new!>> "%log%"
set "ver=!new!"
goto :eof
